### ISSUE TITLE
首页“Web API 服务”下方文字错误

### ISSUE THREAD

**Issue by afei00615** [vertx-china/vertx-web-site#324]
现在翻译是“直接连接您的OpenAPI 3的web路由器到事件总线服务”，实际上应该和openapi3没关系，英文是“Helps you handle HTTP requests using the Vert.x event bus.”，应该是帮你使用event bus处理http请求

**Comment by okou19900722** [comment]
你好，感谢你的反馈，不过目前文档的版本是4.4.0。4.4.1之后修改了这个描述(见PR[145](https://github.com/vertx-web-site/vertx-web-site.github.io/pull/145))，目前暂时没人维护翻译项目

**Comment by afei00615** [comment]
好吧，不过这个翻译已经很好了，感谢各位
ps：我们还是本家呢
